//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracker.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobTrackerBusinessErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobTrackerBusinessErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobTracker.Business.JobTrackerBusinessErrors", typeof(JobTrackerBusinessErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding profile invalid..
        /// </summary>
        internal static string AddProfileError {
            get {
                return ResourceManager.GetString("AddProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job action doesn&apos;t exist..
        /// </summary>
        internal static string EmployerActionsNotExist {
            get {
                return ResourceManager.GetString("EmployerActionsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer detail doesn&apos;t exist..
        /// </summary>
        internal static string EmployerDetailsNotExist {
            get {
                return ResourceManager.GetString("EmployerDetailsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging data invalid..
        /// </summary>
        internal static string EmployerPagingError {
            get {
                return ResourceManager.GetString("EmployerPagingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer profile already exist..
        /// </summary>
        internal static string EmployerProfileExist {
            get {
                return ResourceManager.GetString("EmployerProfileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer profile doesn&apos;t exist..
        /// </summary>
        internal static string EmployerProfileNotExist {
            get {
                return ResourceManager.GetString("EmployerProfileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer profiles doesn&apos;t exist..
        /// </summary>
        internal static string EmployerProfilesNotExist {
            get {
                return ResourceManager.GetString("EmployerProfilesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Action doesn&apos;t exist..
        /// </summary>
        internal static string JobActionNotExist {
            get {
                return ResourceManager.GetString("JobActionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job profile already exist..
        /// </summary>
        internal static string JobProfileExist {
            get {
                return ResourceManager.GetString("JobProfileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job profile doesn&apos;t exist..
        /// </summary>
        internal static string JobProfileNotExist {
            get {
                return ResourceManager.GetString("JobProfileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job profiles doesn&apos;t exist..
        /// </summary>
        internal static string JobProfilesNotExist {
            get {
                return ResourceManager.GetString("JobProfilesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist..
        /// </summary>
        internal static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username was invalid..
        /// </summary>
        internal static string UsernameError {
            get {
                return ResourceManager.GetString("UsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist.
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
